import Home from "./Home";
import Login from "./Login";
import Signup from "./Signup";
import ForgotPass from "./ForgotPass";
import Error from "./Error";
import Courses from "./Courses";
import CourseIndividual from "./CourseIndividual";
import Profile from "./Profile";
import Settings from "./Settings";
import AboutUs from "./About";
import TermsOfUse from "./Terms";
import Cookies from "./Cookies";
import Privacy from "./Privacy";
import Contact from "./Contact";
import MyCourses from "./MyCourses";
import CreateCourse from "./teacherPages/CreateCourse";
import AdminDashboard from "./adminPages/AdminDashboard";
import AllUsers from "./adminPages/AllUsers";
import AddVideo from "./teacherPages/AddVideo";
import Reports from "./adminPages/Reports";
import Streaming from "./Streaming";

export {Login,Signup,Home,ForgotPass,Error,Courses,Reports,AllUsers,AddVideo,CourseIndividual,Profile,Settings,Streaming,AboutUs,TermsOfUse,Cookies,Privacy,Contact,MyCourses,CreateCourse,AdminDashboard}; 